// packages/widgets/react/src/index.tsx
import { useEffect, useRef } from 'react';

type Props = { site: string; theme?: 'dark' | 'light' | 'auto'; page: string; host?: string };
export default function index({
	site,
	theme,
	page,
	host = 'https://convocomet.dev/widget'
}: Props) {
	useEffect(() => {
		window.addEventListener('message', (e) => {
			if (e.data.type === 'resize') {
				iframe.current.height = e.data.height;
			}
		});
		iframe.current.contentWindow.postMessage(
			{
				type: 'resizerInit'
			},
			'*'
		);
	}, []);
	const iframe = useRef(null) as {
		current: HTMLIFrameElement;
	};
	const searchparams = new URLSearchParams({
		site,
		page
	});
	if (theme) searchparams.append('theme', theme);
	return (
		<iframe
			ref={iframe}
			loading="lazy"
			style={{
				width: '100%',
				border: '0'
			}}
			title={'Comments by ConvoComet'}
			src={`${host}?${searchparams.toString()}`}
		/>
	);
}

// packages/widgets/svelte/src/index.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let iframe: HTMLIFrameElement;
	export let page: string;
	export let site: string;
	export let host: string = 'https://convocomet.dev/widget';
	export let theme: 'light' | 'auto' | 'dark' = undefined;
	onMount(() => {
		window.addEventListener('message', (e) => {
			if (e.data.type === 'resize') {
				iframe.height = e.data.height;
			}
		});
		iframe.contentWindow.postMessage(
			{
				type: 'resizerInit'
			},
			'*'
		);
	});
	const params = new URLSearchParams({
		site,
		page,
		theme
	});
</script>

<iframe
	bind:this={iframe}
	loading="lazy"
	style="width:100%;border:0;"
	title={'Comments by ConvoComet'}
	allowtransparency={true}
	src={`${host}?${params.toString()}`}
/>
